### ISSUE TITLE
Protocol documentation

### ISSUE THREAD

**Issue by just-doit** [osintaj/PioneerDesktopControl#1]
Hello,
I came across your project here on GitHub because I was looking for a description of the protocol for remotely controlling the XC-HM71.
Do you have any documentation on this?

**Comment by osintaj** [comment]
Hi, I have reverse-engineered that only. But I have just found this project on github where you can find description of some commands (not all are working for X-HM71):

[https://github.com/mhop/fhem-mirror/blob/master/fhem/FHEM/70_PIONEERAVR.pm](https://github.com/mhop/fhem-mirror/blob/master/fhem/FHEM/70_PIONEERAVR.pm)
